name: 스프링 CICD 연습

on:
  push:
    branches: main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH로 EC2 접속
        uses: appleboy/ssh-action@v1.2.1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script_stop: true
          script: |
            cd /home/ubuntu/git-actions
            sudo git pull origin main
            sudo ./mvnw clean package
            sudo fuser -k -n tcp 8080 || true
            nohup java -jar ./target/*SNAPSHOT.jar > ./output.log 2>&1 &
